### ISSUE TITLE
Auto renew doesn't work...

### ISSUE THREAD

**Issue by tstivers1990** [wmnnd/nginx-certbot#9]
Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait 31944{!}; done;'\": stat /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait 31944{!}; done;': no such file or directory": unknown

Running on Container Optimized OS.

**Comment by tstivers1990** [comment]
The only way I found to resolve this was by creating my own image with this as the entrypoint.

https://hub.docker.com/r/tstivers/certbot-autorenew

**Comment by wmnnd** [comment]
Not sure what the issue could be, maybe it’s related to `$$` being replaced with the actual PID too early.

Original configuration:
```
"/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
```
Configuration from your error string:
```
"/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait 31944{!}; done;'"
```

But since you’ve found a solution for this, I’ll close the issue for now.

**Comment by MaximilianKohler** [comment]
I'm using this https://yasoob.me/posts/setting-up-listmonk-opensource-newsletter-mailing/#setting-up-ssl which uses your directions, and mine didn't auto-renew. I had to run `sudo bash ./init-letsencrypt.sh` again to get it to renew. 

I also had run this command previously:

`SLEEPTIME=$(awk 'BEGIN{srand(); print int(rand()*(3600+1))}'); echo "0 0,12 * * * root sleep $SLEEPTIME && certbot renew -q" | sudo tee -a /etc/crontab > /dev/null` 

per https://certbot.org/renewal-setup. But I guess that's not the correct method. 

---

**EDIT**: The issue was the the directions were incomplete and the certbot container wasn't running. `sudo docker start certbot` fixed it. https://github.com/knadh/listmonk/issues/120#issuecomment-1314110010

**Comment by MaximilianKohler** [comment]
I tried typing in the renew command manually `/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'` and got an access error:

```
The following error was encountered:
[Errno 13] Permission denied: '/var/log/letsencrypt/.certbot.lock'
Either run as root, or set --config-dir, --work-dir, and --logs-dir to writeable paths.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/tmpamhpwmlr/log or re-run Certbot with -v for more details.
/bin/sh: 1: wait: Illegal number: 2586308{!}
```

I redid it with sudo:  `sudo /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'` and got this error:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
No renewals were attempted.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
/bin/sh: 1: wait: Illegal number: 2586486{!}
Saving debug log to /var/log/letsencrypt/letsencrypt.log
```

**Comment by MaximilianKohler** [comment]
Well `sudo docker start certbot` "fixed" my issue by getting certbot to run, but I noticed that another issue is that certbot doesn't restart when you reboot the server. 

I edited `nano ./docker-compose.yml` to include `    restart: unless-stopped`

Right below
```
  certbot:
    image: certbot/certbot
```

But certbot still doesn't restart after rebooting the server. 

**EDIT**: I think it's because it requires this command: `sudo docker-compose stop ; sudo docker-compose up`

After running that command for something else, `certbot` was automatically restarted after I rebooted my server.
